apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
    service.kubernetes.io/topology-aware-hints: auto
  creationTimestamp: "2025-08-02T11:52:01Z"
  labels:
    k8s-app: kube-dns
    k8slens-edit-resource-version: v1
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
    type: ClusterIp
  name: kube-dns
  namespace: kube-system
  resourceVersion: "166927"
  uid: af94a58b-c0ee-417f-94b8-f17f4b5cc977
spec:
  clusterIP: 10.96.0.10
  clusterIPs:
  - 10.96.0.10
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}