# playbooks/deploy-local-path-storage.yml

- name: Deploy Rancher local-path provisioner and patch default StorageClass
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig_path: ~/.kube/config

  tasks:
    - name: Deploy local-path-provisioner
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        src: https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml

    - name: Wait for local-path-provisioner pod to be ready
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: local-path-storage
        label_selectors:
          - app=local-path-provisioner
        kubeconfig: "{{ kubeconfig_path }}"
      register: provisioner_pods
      until: provisioner_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length > 0
      retries: 10
      delay: 6

    - name: Patch default StorageClass annotation
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        kind: StorageClass
        api_version: storage.k8s.io/v1
        name: local-path
        definition:
          metadata:
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"