- name: Install Helm on Kubernetes nodes
  hosts: k8s_cluster
  become: true
  tasks:
    - name: Download Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Run Helm install script
      command: /tmp/get_helm.sh

    - name: Verify helm is installed
      command: helm version
      register: helm_version
      changed_when: false

    - name: Print helm version
      debug:
        var: helm_version.stdout