- name: Create ingress-nginx namespace
  kubernetes.core.k8s:
    state: present
    kind: Namespace
    name: ingress-nginx

- name: Add ingress-nginx Helm repository
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Install ingress-nginx via Helm with hostPort configuration
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: false
    values:
      controller:
        kind: DaemonSet
        hostPort:
          enabled: true
          ports:
            http: 80
            https: 443
        ingressClassResource:
          name: nginx
          enabled: true
        ingressClass: nginx
        nodeSelector: {}
        tolerations: []