apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubble-relay
  namespace: kube-system
  uid: 222bc40d-92ed-4435-9545-0ddc080be2b2
  resourceVersion: '115757'
  generation: 1
  creationTimestamp: '2025-07-29T06:12:26Z'
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hubble-relay
    app.kubernetes.io/part-of: cilium
    k8s-app: hubble-relay
  annotations:
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  selfLink: /apis/apps/v1/namespaces/kube-system/deployments/hubble-relay
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-07-29T06:12:26Z'
      lastTransitionTime: '2025-07-29T06:12:26Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-07-29T06:12:48Z'
      lastTransitionTime: '2025-07-29T06:12:26Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "hubble-relay-6b6fd4ffb4" has successfully progressed.
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: hubble-relay
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: hubble-relay
        app.kubernetes.io/part-of: cilium
        k8s-app: hubble-relay
    spec:
      volumes:
        - name: config
          configMap:
            name: hubble-relay-config
            items:
              - key: config.yaml
                path: config.yaml
            defaultMode: 420
        - name: tls
          projected:
            sources:
              - secret:
                  name: hubble-relay-client-certs
                  items:
                    - key: tls.crt
                      path: client.crt
                    - key: tls.key
                      path: client.key
                    - key: ca.crt
                      path: hubble-server-ca.crt
            defaultMode: 256
      containers:
        - name: hubble-relay
          image: >-
            quay.io/cilium/hubble-relay:v1.17.6@sha256:7d17ec10b3d37341c18ca56165b2f29a715cb8ee81311fd07088d8bf68c01e60
          command:
            - hubble-relay
          args:
            - serve
          ports:
            - name: grpc
              containerPort: 4245
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /etc/hubble-relay
            - name: tls
              readOnly: true
              mountPath: /var/lib/hubble-relay/tls
          livenessProbe:
            grpc:
              port: 4222
              service: ''
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 12
          readinessProbe:
            grpc:
              port: 4222
              service: ''
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            grpc:
              port: 4222
              service: ''
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 20
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: hubble-relay
      serviceAccount: hubble-relay
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 65532
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  k8s-app: cilium
              topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
